[versions]
# Required stuff, https://fabricmc.net/develop/
minecraft = "1.21.5"
yarnMappings = "1.21.5+build.1"
fabricLoader = "0.16.14"
fabricApi = "0.127.1+1.21.5"

# Plugins
loom = "1.11-SNAPSHOT" # https://github.com/FabricMC/fabric-loom/releases

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarnMappings" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }


[bundles]


[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }